-- 1.Total Revenue per branch
-- This query calculates the total revenue generated by each branch
-- It was arranged in descending order 
SELECT branch, SUM(total_price) AS total_revenue 
FROM SUPERMARKET_SALES
GROUP by branch
ORDER by total_revenue DESC; 

-- 2.Total Revenue per product Category
-- This query calculates the total revenue generated by each product category. 
-- The taotal revenue was arranged in descending order
SELECT product_category, SUM(total_price) AS category_revenue
from SUPERMARKET_SALES
group by product_category
order by category_revenue DESC;

-- 3.Analysis of Customer Type
-- This query calculates the total sales,average transaction value , number of transactions 
-- for each customer type. 
select customer_type, count(*) as customer_count,SUM (total_price)AS Total_sales, Round(AVG(total_price),2) as avg_transaction
from SUPERMARKET_SALES
group by customer_type

-- 4.Gender Sales Comparison 
-- This query calculates the average transaction value for each gender
select gender, ROUND(AVG(total_price), 2) AS avg_transaction
from SUPERMARKET_SALES
group by gender

-- 5.Reward points per product category
-- This query calculates the total reward points earned by customers for each product category.
-- It was ordered in descending order. 
SELECT product_category, SUM(reward_points) AS total_reward_point
from SUPERMARKET_SALES
group by product_category
order by total_reward_point DESC;

-- 6. Total Sales per product 
-- This query calculates the total sales generated per individual products. 
-- It helps identify which product generated the highest revenue. 
Select product_name, sum(total_price) AS product_sales 
from SUPERMARKET_SALES
group by product_name
order by product_sales DESC;

-- 7.Highest product sold by quantity
-- This query calculates the total quanity sold per individual products. 
-- It helps identify the most popular product. 
SELECT product_name, sum(quantity) AS total_units_sold 
from SUPERMARKET_SALES
group by product_name
order by total_units_sold DESC;

-- 8.Average transaction per city 
-- This query calculates the avaerage transaction value for each city 
-- It groups the sales by city to understand how much customers are spending on average in each city. 
SELECT city, ROUND(avg(total_price),2) AS avg_transaction
from SUPERMARKET_SALES
group by city
order by avg_transaction DESC;
Z